[package]
name = "num-prime"
version = "0.4.3"
edition = "2018"

repository = "https://github.com/cmpute/num-prime"
keywords = ["mathematics", "primes", "number-theory", "bigint", "num"]
categories = ["cryptography", "science", "algorithms"]
documentation = "https://docs.rs/num-prime"
license = "Apache-2.0"
description = """
Generic and optimized primality test, factorization and various number theoretic functions with arbitrary precision based on `num`.
"""
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = { version = "0.1.44", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
num-modular = { version = "0.5.0", default-features = false }
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
rand = { version = "0.8.4", default-features = false, features = ["getrandom"] }
lru = { version = "0.7.2", default-features = false }
either = { version = "1.6.1", default-features = false }

[dependencies.num-bigint]
optional = true
version = "0.4.3"
features = ["rand"]

[features]
default = ['std', 'big-table', 'big-int']
std = ['rand/std', 'rand/std_rng']
big-table = []
# TODO: use the new cargo feature to override the num-bigint option
big-int = ['num-bigint', 'num-modular/num-bigint']

[workspace]
members = ["bench"]

[package.metadata.docs.rs]
all-features = true
